# Generated by Django 5.0.4 on 2024-05-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='estudiante_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cursos.estudiante'),
        ),
    ]
