# Generated by Django 5.0.4 on 2024-05-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_direccion_estudiante_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='estudiante_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cursos.estudiante'),
        ),
    ]
